// Stub — replace by running: npx convex dev
// This file is auto-generated by Convex. Running `npx convex dev` will
// overwrite this stub with the real generated types.

/* eslint-disable @typescript-eslint/no-explicit-any */
export const api: any = new Proxy(
  {},
  {
    get(_t, p) {
      return new Proxy(
        {},
        {
          get(_t2, p2) {
            return `${String(p)}:${String(p2)}`;
          },
        },
      );
    },
  },
);

export const internal: any = api;
