// Stub — replace by running: npx convex dev
// This file is auto-generated by Convex. Running `npx convex dev` will
// overwrite this stub with the real generated types.

/* eslint-disable @typescript-eslint/no-explicit-any */
export const query = (def: any) => def;
export const mutation = (def: any) => def;
export const action = (def: any) => def;
export const internalQuery = (def: any) => def;
export const internalMutation = (def: any) => def;
export const internalAction = (def: any) => def;
export const httpRouter = () => ({ route: () => {}, runRequest: () => {} });
export type QueryCtx = any;
export type MutationCtx = any;
export type ActionCtx = any;
export type DatabaseReader = any;
export type DatabaseWriter = any;
